# Generated by Django 4.2.3 on 2023-10-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_comments_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='img_url',
            field=models.CharField(default='https://miro.medium.com/v2/resize:fit:600/0*jGmQzOLaEobiNklD', max_length=800),
        ),
    ]
