# Generated by Django 4.2.3 on 2023-10-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=299)),
            ],
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='category',
        ),
    ]
