# Generated by Django 4.2.3 on 2023-10-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_remove_auctionlisting_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
