# Generated by Django 4.2.3 on 2023-10-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlisting_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='img_url',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='item_img',
            field=models.ImageField(default='placehold.jpg', upload_to='pics'),
        ),
    ]
