# Generated by Django 4.2.3 on 2023-10-27 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_auctionlisting_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='item_img',
            field=models.ImageField(default='pictures/placehold.jpg', upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bider', to=settings.AUTH_USER_MODEL),
        ),
    ]
